package com.techie.domain.entities;

import jakarta.persistence.*;
import lombok.*;

import java.sql.*;

/**
 * Entity representing persistent login tokens for the "Remember Me" functionality.
 * This table is used by Spring Security to store and retrieve remember-me tokens,
 * allowing users to stay logged in across browser sessions.
 */
@Setter
@Getter
@NoArgsConstructor
@Entity
@Table(name = "persistent_logins")
public class PersistentLogin {

    /**
     * The series identifier for the remember-me token.
     * This is used as the primary key and is generated by Spring Security.
     */
    @Id
    private String series;

    /**
     * The username of the user associated with this remember-me token.
     * This allows Spring Security to identify which user the token belongs to.
     */
    @Column(nullable = false, unique = true)
    private String username;

    /**
     * The actual remember-me token value.
     * This is used to validate the remember-me cookie sent by the client.
     */
    @Column(nullable = false)
    private String token;

    /**
     * Timestamp of when this token was last used.
     * This helps in determining if the token is still valid or has expired.
     */
    @Column(name = "last_used", nullable = false)
    private Timestamp lastUsed;
}